export const USER_ACTION_TYPES = {
  CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
  GOOGLE_SIG_IN_START: 'user/GOOGLE_SIG_IN_START',
  EMAIL_SIG_IN_START: 'user/EMAIL_SIG_IN_START',
  SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'user/SIGN_IN_FAILED',
};
